services:
    db:
        build: ./database
        container_name: site-cead-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - /srv/volumes/cead/mysql:/var/lib/mysql
        networks:
            - site-cead-net

    wordpress:
        image: wordpress:php8.2-fpm
        container_name: site-cead-app
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
            - /srv/volumes/cead/wordpress:/var/www/html
        depends_on:
            - db
        networks:
            - site-cead-net

    nginx:
        image: nginx:alpine
        container_name: site-cead-nginx
        restart: unless-stopped
        ports:
            - "8090:80"
        volumes:
            - /srv/volumes/cead/wordpress:/var/www/html:ro
            - /srv/site-docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /srv/site-docker/nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
            - wordpress
        networks:
            - site-cead-net

networks:
    site-cead-net:
