location ~ /\.(?!well-known) {
    return 444;
}

location = /xmlrpc.php {
    return 444;
}

location ~* ^/wp-content/uploads/.*\.php$ {
    return 444;
}

location = /wp-config.php {
    return 444;
}

location ~* ^/readme\.html$ {
    return 444;
}

location ~* ^/license\.txt$ {
    return 444;
}

location ~* ^/wp-admin/includes/ {
    return 444;
}

location ~* ^/wp-includes/theme-compat/ {
    return 444;
}

location ~* ^/wp-includes/js/tinymce/langs/.*\.php$ {
    return 444;
}

# Prevent any potentially-executable files in the uploads directory from being executed
# by forcing their MIME type to text/plain
location ~* ^/wp-content/uploads/.*\.(html|htm|shtml|php|js|swf)$ {
    types { }
    default_type text/plain;
}
